### ISSUE TITLE
running seed fails on windows

### ISSUE THREAD

**Issue by idursun** [OutWatch/seed.g8#1]
Hi,

running 
```
sbt new outwatch/seed.g8 
```
fails with the following message on windows

```
org.eclipse.jgit.dircache.InvalidPathException: Invalid path: src/main/g8/src/main/scala/$name;format="Camel"$.scala
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkValidPathSegment(DirCacheCheckout.java:1308)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkValidPath(DirCacheCheckout.java:1277)
        at org.eclipse.jgit.dircache.DirCacheCheckout.processEntry(DirCacheCheckout.java:314)
        at org.eclipse.jgit.dircache.DirCacheCheckout.prescanOneTree(DirCacheCheckout.java:293)
        at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:411)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
        at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:251)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
        at giter8.JgitHelper$.clone(JgitHelper.scala:114)
        at giter8.JgitHelper$.run(JgitHelper.scala:65)
        at giter8.JgitHelper$.run(JgitHelper.scala:78)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
        at scala.Option.map(Option.scala:145)
        at giter8.Giter8.run(giter8.scala:33)
        at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
        at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
        at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
        at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
        at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
        at scala.collection.immutable.List.find(List.scala:84)
        at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
        at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
        at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: org.eclipse.jgit.errors.CorruptObjectException: name contains '"'
        at org.eclipse.jgit.lib.ObjectChecker.scanPathSegment(ObjectChecker.java:417)
        at org.eclipse.jgit.lib.ObjectChecker.checkPathSegment(ObjectChecker.java:476)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkValidPathSegment(DirCacheCheckout.java:1305)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkValidPath(DirCacheCheckout.java:1277)
        at org.eclipse.jgit.dircache.DirCacheCheckout.processEntry(DirCacheCheckout.java:314)
        at org.eclipse.jgit.dircache.DirCacheCheckout.prescanOneTree(DirCacheCheckout.java:293)
        at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:411)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
        at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:251)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
        at giter8.JgitHelper$.clone(JgitHelper.scala:114)
        at giter8.JgitHelper$.run(JgitHelper.scala:65)
        at giter8.JgitHelper$.run(JgitHelper.scala:78)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
        at scala.Option.map(Option.scala:145)
        at giter8.Giter8.run(giter8.scala:33)
        at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
        at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
        at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
        at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
        at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
        at scala.collection.immutable.List.find(List.scala:84)
        at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
        at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
        at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] org.eclipse.jgit.dircache.InvalidPathException: Invalid path: src/main/g8/src/main/scala/$name;format="Camel"$.scala
```

**Comment by LukaJCB** [comment]
That's pretty odd, you ARE using version 13.13 correct? I'll have a look at this shortly :)

**Comment by idursun** [comment]
Yes I do use sbt 13.13 

I tried it on Windows 10 and with turkish regional settings.

**Comment by LukaJCB** [comment]
Okay thank you, I'll hope to be able to give you an update asap!

**Comment by piton4k** [comment]
Hi, I wanted to give OutWatch a try and ran into this issue as well. It's a windows issue since it doesn't allow `"` in filenames (even `git clone` fails with the same error). See more [here](https://github.com/foundweekends/giter8/issues/130).

**Comment by LukaJCB** [comment]
Fixed thanks to the great work from @piton4k. Thank you so much! :)
